<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Sequence" nsURI="Sequence" nsPrefix="Sequence">
  <eClassifiers xsi:type="ecore:EClass" name="SequenceDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequence" upperBound="-1"
        eType="#//Sequence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lifeline" upperBound="-1"
        eType="#//Lifeline" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lifeline">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//Lifeline"/>
  <eClassifiers xsi:type="ecore:EClass" name="internObject" eSuperTypes="#//Lifeline"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence"/>
  <eClassifiers xsi:type="ecore:EClass" name="message" eSuperTypes="#//Sequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#//Operation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="soure" lowerBound="1" eType="#//Lifeline"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Destination" lowerBound="1"
        eType="#//Lifeline"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationMessage" eSuperTypes="#//message"/>
  <eClassifiers xsi:type="ecore:EClass" name="SignalMessage" eSuperTypes="#//message"/>
  <eClassifiers xsi:type="ecore:EClass" name="Combinedfragement" eSuperTypes="#//Sequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interactionoperand" lowerBound="1"
        upperBound="-1" eType="#//InteractionOperand" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Guard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="loop" eSuperTypes="#//Combinedfragement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Alt" eSuperTypes="#//Combinedfragement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Opt" eSuperTypes="#//Combinedfragement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReplyMessage" eSuperTypes="#//message"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametre" lowerBound="1"
        upperBound="-1" eType="#//parametre" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NameVariable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="parametre">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionOperand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequence" upperBound="-1"
        eType="#//Sequence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Guard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
