<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SequenceV2" nsURI="SequenceV2" nsPrefix="SequenceV2">
  <eClassifiers xsi:type="ecore:EClass" name="Message" eSuperTypes="#//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#//Operation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//LifeLine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//LifeLine"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//MessageKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lifeLines" lowerBound="1"
        upperBound="-1" eType="#//LifeLine" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" lowerBound="1"
        upperBound="-1" eType="#//InteractionFragment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LifeLine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractobject" lowerBound="1"
        eType="#//AbstractObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractObject" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//AbstractObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="#//AbstractObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" upperBound="-1"
        eType="#//Param" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnVariable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Param">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="argName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="argType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionFragment" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CombinedFragment" eSuperTypes="#//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operands" lowerBound="1"
        upperBound="-1" eType="#//InteractionOperand" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interactionOperator" eType="#//OperatorKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionOperand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragmentOperands" lowerBound="1"
        upperBound="-1" eType="#//InteractionFragment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperatorKind">
    <eLiterals name="opt"/>
    <eLiterals name="alt" value="1"/>
    <eLiterals name="loop" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MessageKind">
    <eLiterals name="operation"/>
    <eLiterals name="signal" value="1"/>
    <eLiterals name="reply" value="2"/>
  </eClassifiers>
</ecore:EPackage>
