<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Sequence" nsURI="Sequence" nsPrefix="Sequence">
  <eClassifiers xsi:type="ecore:EClass" name="SequenceDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequence" upperBound="-1"
        eType="#//Sequence" containment="true" eOpposite="#//Sequence/sequenceDiagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lifeline" lowerBound="1"
        upperBound="-1" eType="#//Lifeline" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lifeline">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//Lifeline"/>
  <eClassifiers xsi:type="ecore:EClass" name="internObject" eSuperTypes="#//Lifeline"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequenceDiagram" lowerBound="1"
        eType="#//SequenceDiagram" eOpposite="#//SequenceDiagram/sequence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="message" eSuperTypes="#//Sequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#//Operation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//Lifeline"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dest" lowerBound="1" eType="#//Lifeline"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationMessage" eSuperTypes="#//message"/>
  <eClassifiers xsi:type="ecore:EClass" name="SignalMessage" eSuperTypes="#//message"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReplyMessage" eSuperTypes="#//message"/>
  <eClassifiers xsi:type="ecore:EClass" name="Combinedfragement" eSuperTypes="#//Sequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interactionOperand" lowerBound="1"
        upperBound="-1" eType="#//InteractionOperand" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="loop" eSuperTypes="#//Combinedfragement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Alt" eSuperTypes="#//Combinedfragement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Opt" eSuperTypes="#//Combinedfragement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametre" lowerBound="1"
        upperBound="-1" eType="#//Parametre" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameVariable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parametre">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionOperand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequence" upperBound="-1"
        eType="#//Sequence"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guard" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
