<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="activityModel" nsURI="activitymodel" nsPrefix="activitymodel">
  <eClassifiers xsi:type="ecore:EClass" name="Start" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityDiagramToStart"
        lowerBound="1" eType="#//ActivityDiagram" eOpposite="#//ActivityDiagram/initial"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityDiagram">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" lowerBound="1"
        upperBound="-1" eType="#//Activity" containment="true" eOpposite="#//Activity/activityDiagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initial" eType="#//Start"
        eOpposite="#//Start/activityDiagramToStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityDiagram" lowerBound="1"
        eType="#//ActivityDiagram" eOpposite="#//ActivityDiagram/activities"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingEdges" upperBound="-1"
        eType="#//Edge" eOpposite="#//Edge/dest"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingEdges" upperBound="-1"
        eType="#//Edge" eOpposite="#//Edge/src"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//Activity"
        eOpposite="#//Activity/outgoingEdges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dest" lowerBound="1" eType="#//Activity"
        eOpposite="#//Activity/incomingEdges"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Join" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="close" lowerBound="1" eType="#//Fork"
        eOpposite="#//Fork/open"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fork" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="open" lowerBound="1" eType="#//Join"
        eOpposite="#//Join/close"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="End" eSuperTypes="#//Activity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Decision" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="close" lowerBound="1" eType="#//Merge"
        eOpposite="#//Merge/open"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Merge" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="open" lowerBound="1" eType="#//Decision"
        eOpposite="#//Decision/close"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SendSignal" eSuperTypes="#//Signal"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReceiveSignal" eSuperTypes="#//Signal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signals" eType="#//Signal"
        eOpposite="#//Signal/objects"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signal" abstract="true" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" lowerBound="1"
        upperBound="-1" eType="#//Object" eOpposite="#//Object/signals"/>
  </eClassifiers>
</ecore:EPackage>
