<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="activitymodel" nsURI="activitymodel" nsPrefix="activitymodel">
  <eClassifiers xsi:type="ecore:EClass" name="Start" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activitydiag" lowerBound="1"
        eType="#//ActivityDiagram"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityDiagram">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" lowerBound="1"
        upperBound="-1" eType="#//Activity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initial" lowerBound="1"
        eType="#//Start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activitydiagram" lowerBound="1"
        eType="#//ActivityDiagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingedges" upperBound="-1"
        eType="#//Edge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingedges" upperBound="-1"
        eType="#//Edge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dst" lowerBound="1" eType="#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Join" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="close" lowerBound="1" eType="#//Fork"
        eOpposite="#//Fork/open"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fork" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="open" lowerBound="1" eType="#//Join"
        eOpposite="#//Join/close"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="End" eSuperTypes="#//Activity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Decision" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="openclose" lowerBound="1"
        eType="#//Merge" eOpposite="#//Merge/openclose"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Merge" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="openclose" lowerBound="1"
        eType="#//Decision" eOpposite="#//Decision/openclose"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SendSignal" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" lowerBound="1"
        upperBound="-1" eType="#//Object"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReceiveSignal" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" lowerBound="1"
        upperBound="-1" eType="#//Object"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendsignal" lowerBound="1"
        eType="#//SendSignal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receivesignal" lowerBound="1"
        eType="#//ReceiveSignal"/>
  </eClassifiers>
</ecore:EPackage>
